### ISSUE TITLE
ThemePackage.activateConfig is deprecated.

### ISSUE THREAD

**Issue by mustafagursel** [orderedlist/unity-ui#65] opened 2015-05-06 12:56 UTC
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
ThemePackage.activateConfig (D:\Users\mgursel\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:247:11)
ThemePackage.activateNow (D:\Users\mgursel\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:218:14)
<unknown> (D:\Users\mgursel\AppData\Local\atom\app-0.196.0\resources\app.asar\src\theme-package.js:48:26)
ThemePackage.measure (D:\Users\mgursel\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
```

**Comment by orderedlist** [comment] 2015-05-06 14:13
Dupe of #64.

**Closed by orderedlist** 2015-05-06 14:13 UTC
